### ISSUE TITLE
Issue with Event Listener Not Firing Consistently

### ISSUE THREAD

**Issue by realyukii** [hansputera/gampang#10]
I am experiencing an issue with the event listener for the on `message` event. The event listener is not firing consistently. Sometimes, I need to delete the session and generate a new one before the event listener will fire. However, even after doing this, the event listener still does not fire sometimes. When this happens, I need to repeat the process of deleting and generating a new session.

I suspect that this issue may be caused by a corrupted session. However, this is just an assumption at this point. I will try to investigate further when I have more time.

Also, I've make sure the connection was stable

**Comment by realyukii** [comment]
related links: https://discord.com/channels/725839806084546610/1223502988409180300/1223502988409180300

**Comment by hansputera** [comment]
Thanks for report, I'll label it as a bug, and I'd investigate on it

**Comment by hansputera** [comment]
Fixed. Please check latest version (2.3.1)
Thanks
