### ISSUE TITLE
cara send message untuk blast (tapi bukan mass-blast) ?

### ISSUE THREAD

**Issue by HaraHQ** [hansputera/gampang#11]
ada contoh code untuk kirim langsung gak misal saya mau kirim notifikasi ke user id tertentu ? kyk ngirim expiration notice gitu ?

kalo saya liat ada di Context untuk send message, cuma saya ngerti nya isi Context itu ada client, tapi setelah nya itu saya kurang paham dapat darimana (di bagian rawMessage IWebMessageInfo)

**Comment by hansputera** [comment]
Halo mas, untuk mengirim message atau pesan secara single target di versi saat ini belum ada. Namun sudah saya tambahkan di versi terbaru. Silahkan dicek mas..

Untuk example code, saya lampirkan sebagai berikut:
```ts
import { sendMessageTo, sendMessagesTo } from 'gampang';

// const client = new Client(....)
// we've initialized the Gampang client and Session Manager here...

(async () => {
  const context = await sendMessageTo(client, '123456789@s.whatsapp.net', {
   text: 'Hello World!',
 });
 // context = Context

 const broadcasts = [{
   jid: '123456789@s.whatsapp.net',
   text: 'Hi! Your OTP Code is: 1234',
 }, {
  jid: '123444@s.whatsapp.net',
 text: 'Hi! Your Code Verification On MyPertamina is 09123',
 }];
 const contexts = await sendMessagesTo(client, broadcasts);
 // contexts = Array<Context>
})();
```
