### ISSUE TITLE
[BUG] tidak dapat menerima gambar ketika menggunakan opsi 'web'

### ISSUE THREAD

**Issue by ahmadxgani** [hansputera/gampang#5]
server tidak memberikan response saat browser melakukan request seperti pada gambar di bawah (empty response):
![image](https://user-images.githubusercontent.com/73988956/208653628-52915f7c-edc8-46d2-8d77-b3dc09ab32ea.png)

apakah ada kesalahan pada code saya?

```javascript
const client = new Client(session, {
  'qr': {
    'store': 'web',
    'options': {
      'port': 3000
    },
  },
  'prefixes': ['.'],
});
```

**Comment by hansputera** [comment]
This issue was fixed on v1.6.8
