### ISSUE TITLE
QR not fired

### ISSUE THREAD

**Issue by zennn08** [hansputera/gampang#9]
![image](https://user-images.githubusercontent.com/75623219/236607583-5f930cfe-0078-41d9-b9b7-d9ea78355ad1.png)

code
```ts
import { Client, SessionManager } from "gampang"

const session = new SessionManager("session")

const client = new Client(session, {
  qr: {
    store: "terminal"
  },
  prefixes: [".", "#", "!", "@", "$", "%"] // add more
})

client.launch()

```

**Comment by hansputera** [comment]
> ![image](https://user-images.githubusercontent.com/75623219/236607583-5f930cfe-0078-41d9-b9b7-d9ea78355ad1.png)
> 
> code
> 
> ```ts
> import { Client, SessionManager } from "gampang"
> 
> const session = new SessionManager("session")
> 
> const client = new Client(session, {
>   qr: {
>     store: "terminal"
>   },
>   prefixes: [".", "#", "!", "@", "$", "%"] // add more
> })
> 
> client.launch()
> ```

Hello, sorry for my late response. I've fixed it on latest commit, so you can update or upgrade the "gampang" dependency to apply the changes. Feel free to open new issue or reopen this issue if you have any issues with gampang :taco: Thanks!
